# -*- mode: sh -*-
autoload -U promptinit
autoload -U compinit

promptinit
compinit

setopt auto_cd # If argument is not a command but a valid directory then go to that directory.
setopt append_history #  Multiple instances of ZSH append their history immediately on exit.
setopt inc_append_history # Multiple instances of ZSH appends issued commands t
                          # o HISTFILE immediately after they are typed.

setopt hist_no_functions # Remove function definitions from history.
setopt hist_ignore_space # Do not record commands started by a SPC character.
setopt hist_ignore_all_dups # Remove old occurrences of the command being added to history.
setopt interactive_comments # Enable comments in a interactive shell session.
setopt emacs # Emacs editing mode.

# setopt PROMPT_SUBST
# setopt hist_reduce_blanks
# setopt interactive_comments

zstyle ':completion:*' rehash true

alias ipl='perl -de0'
alias cnf=/usr/lib/command-not-found
alias grep='grep --color=auto'
alias ls='ls --color=auto'
alias dl-site='wget --recursive --no-clobber --page-requisites --html-extension --convert-links --restrict-file-names=windows --tries=3 --domains'

if [ -e ${PERLBREW_ROOT} ]; then
  source ${PERLBREW_ROOT}/etc/bashrc
fi
