# -*- mode: sh -*-
autoload -U promptinit
autoload -U compinit

promptinit
compinit

setopt auto_cd # If argument is not a command but a valid directory then go to that directory.
setopt append_history #  Multiple instances of ZSH append their history immediately on exit.
setopt inc_append_history # Multiple instances of ZSH appends issued commands t
                          # o HISTFILE immediately after they are typed.

setopt hist_no_functions # Remove function definitions from history.
setopt hist_ignore_space # Do not record commands started by a SPC character.
setopt hist_ignore_all_dups # Remove old occurrences of the command being added to history.
setopt interactive_comments # Enable comments in a interactive shell session.
setopt emacs # Emacs editing mode.

# setopt PROMPT_SUBST
# setopt hist_reduce_blanks
# setopt interactive_comments

zstyle ':completion:*' rehash true

ABCL_JAR=${SLNC_SHARE_DIR}/abcl-1.3.3/abcl.jar
JAVA_BIN=/usr/bin/java

alias ipl='perl -de0'
alias cnf=/usr/lib/command-not-found
alias grep='grep --color=auto'
alias ls='ls --color=auto'
alias sbcl='rlwrap sbcl'
alias ccl='rlwrap ccl'
alias abcl="rlwrap  --remember -c -f ~/.abcl-completions -H ~/.abcl-history -s 1000000 ${JAVA_BIN} -server -Xrs -cp ${ABCL_JAR} org.armedbear.lisp.Main -b"
alias dl-site='wget --content-disposition --recursive --no-clobber --page-requisites --html-extension --convert-links --restrict-file-names=windows --tries=3 --domains'

if [ -e ${PERLBREW_ROOT} ]; then
  source ${PERLBREW_ROOT}/etc/bashrc
fi
alias dl-page='wget --content-disposition --no-clobber --page-requisites --html-extension --convert-links --restrict-file-names=windows --tries=3'
