# -*- sh -*-

autoload -U promptinit
autoload -U compinit

promptinit
compinit

setopt auto_cd # If argument is not a command but a valid directory then go to that directory.
setopt append_history #  Multiple instances of ZSH append their history immediately on exit.
setopt inc_append_history # Multiple instances of ZSH appends issued commands t
                          # o HISTFILE immediately after they are typed.

setopt hist_no_functions # Remove function definitions from history.
setopt hist_ignore_space # Do not record commands started by a SPC character.
setopt hist_ignore_all_dups # Remove old occurrences of the command being added to history.
setopt interactive_comments # Enable comments in a interactive shell session.
setopt emacs # Emacs editing mode.
setopt complete_aliases
# setopt PROMPT_SUBST
# setopt hist_reduce_blanks
# setopt interactive_comments

zstyle ':completion:*' rehash true

zstyle ':completion:*' use-cache on
zstyle ':completion:*' cache-path ~/.cache/zsh

CHI_RLWRAP_OPTS="-b {()[],^%\$#@\"\";:''\\|}"
alias ipl='perl -de0'
alias cnf=command-not-found
alias grep='grep --color=auto'
alias ls='ls --color=auto'
alias guile-rl='rlwrap ${CHI_RLWRAP_OPTS} guile'
alias sbcl-rl='rlwrap ${CHI_RLWRAP_OPTS} sbcl'
alias larceny-rl='rlwrap ${CHI_RLWRAP_OPTS} larceny'
alias ccl-rl='rlwrap ${CHI_RLWRAP_OPTS} ccl'
alias dl-site="wget --content-disposition --recursive --no-clobber \
--page-requisites --html-extension --convert-links \
--restrict-file-names=windows --tries=3 --domains"

if [ -e ${PERLBREW_ROOT} ]; then
  source ${PERLBREW_ROOT}/etc/bashrc
fi

alias dl-page="wget --content-disposition --no-clobber \
--page-requisites --html-extension --convert-links \
--restrict-file-names=windows --tries=3"

export HISTSIZE=5000
export SAVEHIST=3000
export HISTFILE=~/.zsh-history
export PS1="%F{blue}%U%F{cyan}%n%u%F{magenta}@%f%U%F{blue}%m%f%u%\
F{red}:%f %F{cyan}%c%f %F{green}%#%f "

# function dl-site () {
#   domain=$(echo "$1" | perl -p -E '$_ =~ s!((https?|ftp)://)?(?<domain>.*?)?(/.*)?!!; print $+{domain} }{')
#   echo "domain -> $domain"
#   echo "url -> $1"

  # wget --content-disposition --recursive --no-clobber \
  #      --page-requisites --html-extension --convert-links \
  #      --restrict-file-names=windows --tries=3 --domains $domain "${@[@]:2:${#@[@]}}"
# }

# function dl-node () {
#   dl-site "${@[@]}" --no-parent
# }

if [ -e "${OPAMROOT}/opam-init/init.zsh" ]; then
   source "${OPAMROOT}/opam-init/init.zsh"
fi
